### ISSUE TITLE
Doesn't seem to actually work?

### ISSUE THREAD

**Issue by artmamedov** [HVision-NKU/StoryDiffusion#103]
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/59179719/0d319de5-c8e4-418d-a92b-3df6b4538de3)

Running through the gradio examples, it doesn't seem to work at all? It's not keeping the character consistent (hair color, clothing, everything is wrong). It doesn't even keep a consistent animation style (the squirrel arts are completely different in every single frame). 

This is using the gradio example selecting the last option from a raw install. Is there something that needs to be adjusted or is this just something that's been cherry picked (with all due respect), but need to know if it's something that's worth exploring or not.

**Comment by Z-YuPeng** [comment]
could you try Unstable？ SDXL seems to work bad in low resolution.

**Comment by artmamedov** [comment]
Unfortunately similar results with Unstable (not as drastic on that last squirrel picture but still the same)
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/59179719/09b538ed-3670-4f63-b763-4098f3956089)

**Comment by artmamedov** [comment]
This is using the very bottom gradio example with defaults, nothing edited

**Comment by Z-YuPeng** [comment]
Possibly, I've identified the issue. Please increase the sample step. Our results were tested on 50 steps.

**Comment by artmamedov** [comment]
Unfortunately very similar. Is it possible some of the other gradio settings are off too? 
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/59179719/a3b82bb6-8cb2-460c-84ba-f7886b9c7af6)

The example on your project page looks great, so it would be nice to be able to reproduce it
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/59179719/e81765bf-6426-49bc-8703-9900726374fc)

**Comment by Z-YuPeng** [comment]
Thanks for your feedback, we find we introduce some bugs in the update. Currently, the problem seems to be fixed in the last code.
![image - 2024-05-22T004650 327](https://github.com/HVision-NKU/StoryDiffusion/assets/49511209/a5bfc2ee-0834-49a8-8835-1caddaae28a1)

**Comment by artmamedov** [comment]
Awesome, pretty straight forward fix. Yep, can reproduce now. Thank you! Great job :)

**Comment by artmamedov** [comment]
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/59179719/fa026492-9445-44cf-8e82-80376c053a5f)
