### ISSUE TITLE
可以直接通过API调用生成图片吗

### ISSUE THREAD

**Issue by aadian** [HVision-NKU/StoryDiffusion#130]
不同过网页提交，而是通过API来提交请求，生成图片

**Comment by aadian** [comment]
不同过网页提交，而是通过API来提交请求，生成图片

**Comment by dubeno** [comment]
i maked an api server and docker image

**Comment by aadian** [comment]
> i maked an api server and docker image
Nice work!
Thank you, dubeno

**Comment by JimWang151** [comment]
> i maked an api server and docker 

Does this been published?

Thanks
