### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by jurimengs** [HVision-NKU/StoryDiffusion#138]
conda activate storydiffusion 时遇到

D:\Java\jdk1.8.0_31\jre\bin;D:\nvm;D:\nodejs;D:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\jurim\AppData\Local\Mi
crosoft\WindowsApps;C:\Users\jurim\AppData\Local\Programs\Microsoft VS Code\bin;D:\nvm;D:\nodejs : 无法将“D:\Java\jdk1
.8.0_31\jre\bin;D:\nvm;D:\nodejs;D:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\jurim\AppData\Local\Microsoft\Wind
owsApps;C:\Users\jurim\AppData\Local\Programs\Microsoft VS Code\bin;D:\nvm;D:\nodejs”项识别为 cmdlet、函数、脚本文件或
可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 653
+ ... .0_31\bin;";D:\Java\jdk1.8.0_31\jre\bin";D:\nvm;D:\nodejs;D:\Program  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\Java\jdk1.8....:\nvm;D:\nodejs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by yuanhongyi** [comment]
I encountered the same problem.
