### ISSUE TITLE
Unable to find model named diffusion_pytorch_model.bin full errors in ticket

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [HVision-NKU/StoryDiffusion#16]
I am having issues being able to download this model

anyone have idea how to fix

(storydiffusion) PS Z:\GIT\StoryDiffusion> & C:/Users/MindExpander/.conda/envs/storydiffusion/python.exe z:/GIT/StoryDiffusion/gradio_app_sdxl_specific_id.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.14)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Loading pipeline components...:  14%|█████████████▏                                                                              | 1/7 [00:00<00:00, 10.25it/s]
Traceback (most recent call last):
  File "z:\GIT\StoryDiffusion\gradio_app_sdxl_specific_id.py", line 430, in <module>
    pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors=True if use_va else False)       
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn        
    return fn(*args, **kwargs)
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\diffusers\models\modeling_utils.py", line 777, in from_pretrained
    model_file = _get_model_file(
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\MindExpander\.conda\envs\storydiffusion\lib\site-packages\diffusers\utils\hub_utils.py", line 272, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\MindExpander\.cache\huggingface\hub\models--SG161222--RealVisXL_V4.0\snapshots\49740684ab2d8f4f5dcf6c644df2b33388a8ba85\unet.
(storydiffusion) PS Z:\GIT\StoryDiffusion>

**Comment by dyter07** [comment]
Got the same error ;)

**Comment by TheMindExpansionNetwork** [comment]
blaaaaaah same issue on the runpod

root@9f3a58df7076:/workspace/StoryDiffusion# python gradio_app_sdxl.py
python: can't open file '/workspace/StoryDiffusion/gradio_app_sdxl.py': [Errno 2] No such file or directory
root@9f3a58df7076:/workspace/StoryDiffusion# python /workspace/StoryDiffusion/gradio_app_sdxl_specific_id.py
photomaker-v1.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 934M/934M [00:25<00:00, 36.1MB/s]
model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 577/577 [00:00<00:00, 4.57MB/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 560/560 [00:00<00:00, 6.91MB/s]
tokenizer/special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 4.37MB/s]
text_encoder_2/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 4.53MB/s]
scheduler/scheduler_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 474/474 [00:00<00:00, 3.49MB/s]
tokenizer_2/special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460/460 [00:00<00:00, 5.50MB/s]
tokenizer_2/tokenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 4.99MB/s]
tokenizer/tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 10.1MB/s]
tokenizer_2/merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.59MB/s]
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.68k/1.68k [00:00<00:00, 11.3MB/s]
vae/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 602/602 [00:00<00:00, 8.22MB/s]
tokenizer/vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 2.57MB/s]
tokenizer/merges.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.71MB/s]
tokenizer_2/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 3.14MB/s]
Fetching 14 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:01<00:00,  7.06it/s]
Loading pipeline components...:  43%|█████████████████████████████████████████████████████████▍                                                                            | 3/7 [00:00<00:00, 28.53it/s]
Traceback (most recent call last):
  File "/workspace/StoryDiffusion/gradio_app_sdxl_specific_id.py", line 430, in <module>
    pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors=True if use_va else False)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1271, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 525, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 777, in from_pretrained
    model_file = _get_model_file(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/hub_utils.py", line 272, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory /root/.cache/huggingface/hub/models--SG161222--RealVisXL_V4.0/snapshots/49740684ab2d8f4f5dcf6c644df2b33388a8ba85/vae.
root@9f3a58df7076:/workspace/StoryDiffusion#

**Comment by Z-YuPeng** [comment]
please, try 
pip install safetensors==0.4.0
I speculate that this might be the issue; I hope to receive feedback again

**Comment by mikeyimer** [comment]
> @TheMindExpansionNetwork @dyter07 please, try pip install safetensors==0.4.0 I speculate that this might be the issue; I hope to receive feedback again
After installing safetensors, it seems there is still the same issue.
![story3](https://github.com/HVision-NKU/StoryDiffusion/assets/137673481/55d9159c-af49-426d-b743-0bb400224d72)

**Comment by Z-YuPeng** [comment]
Sorry to bother you again @mikeyimer  Could you git pull  the newest code and run again?

**Comment by Globalteamspeak** [comment]
> Sorry to bother you again @mikeyimer Could you git pull the newest code and run again?

I had the same issue and the latest git pull has fixed it, thank you.

**Comment by Z-YuPeng** [comment]
It seems that the issue has been resolved. Feel free to reopen if the problem still exists.
