### ISSUE TITLE
python .\gradio_app_sdxl_specific_id.py ERROR

### ISSUE THREAD

**Issue by hkstemcenter** [HVision-NKU/StoryDiffusion#21]
python .\gradio_app_sdxl_specific_id.py
Traceback (most recent call last):
  File "D:\StoryDiffusion\gradio_app_sdxl_specific_id.py", line 2, in <module>
    import gradio as gr
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "C:\Users\aipc2\anaconda3\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1970: illegal multibyte sequence

**Comment by tiwentichat** [comment]
兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda

python gradio_app_sdxl_specific_id.py
Traceback (most recent call last):
  File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in <module>
    import gradio as gr
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

**Comment by tiwentichat** [comment]
> 兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda
> 
> python gradio_app_sdxl_specific_id.py Traceback (most recent call last): File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in import gradio as gr File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio__init__.py", line 3, in import gradio._simple_templates File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates__init__.py", line 1, in from .simpledropdown import SimpleDropdown File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates\simpledropdown.py", line 6, in from gradio.components.base import FormComponent File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components__init__.py", line 40, in from gradio.components.multimodal_textbox import MultimodalTextbox File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in class MultimodalTextbox(FormComponent): File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in **new** create_or_modify_pyi(component_class, name, events) File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi source_code = source_file.read_text() File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

this issue is solved by AI: pip uninstall gradio   then: pip install gradio
but I met another issue: Cache of C disk is not enough at this step:  python gradio_app_sdxl_specific_id.py 
It would download about 40G models T T

上述问题我问了AI，卸载再重装gradio就可以了，应该是版本问题。具体我忘了记下来版本号。。
先：pip uninstall gradio   然后: pip install gradio

但是我遇到了另一个问题：执行python gradio_app_sdxl_specific_id.py 的时候，它要下载大概40G的模型。。。C盘不够用，该咋设置啊我草

**Comment by whmc76** [comment]
> > 兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda
> > python gradio_app_sdxl_specific_id.py Traceback (most recent call last): File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in import gradio as gr File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio__init__.py", line 3, in import gradio._simple_templates File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates__init__.py", line 1, in from .simpledropdown import SimpleDropdown File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates\simpledropdown.py", line 6, in from gradio.components.base import FormComponent File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components__init__.py", line 40, in from gradio.components.multimodal_textbox import MultimodalTextbox File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in class MultimodalTextbox(FormComponent): File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in **new** create_or_modify_pyi(component_class, name, events) File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi source_code = source_file.read_text() File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence
> 
> this issue is solved by AI: pip uninstall gradio then: pip install gradio but I met another issue: Cache of C disk is not enough at this step: python gradio_app_sdxl_specific_id.py It would download about 40G models T T
> 
> 上述问题我问了AI，卸载再重装gradio就可以了，应该是版本问题。具体我忘了记下来版本号。。 先：pip uninstall gradio 然后: pip install gradio
> 
> 但是我遇到了另一个问题：执行python gradio_app_sdxl_specific_id.py 的时候，它要下载大概40G的模型。。。C盘不够用，该咋设置啊我草

兄弟好样的 用你的办法解决了

**Comment by tiwentichat** [comment]
> > > 兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda
> > > python gradio_app_sdxl_specific_id.py Traceback (most recent call last): File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in import gradio as gr File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio__init__.py", line 3, in import gradio._simple_templates File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates__init__.py", line 1, in from .simpledropdown import SimpleDropdown File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates\simpledropdown.py", line 6, in from gradio.components.base import FormComponent File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components__init__.py", line 40, in from gradio.components.multimodal_textbox import MultimodalTextbox File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in class MultimodalTextbox(FormComponent): File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in **new** create_or_modify_pyi(component_class, name, events) File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi source_code = source_file.read_text() File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence
> > 
> > 
> > this issue is solved by AI: pip uninstall gradio then: pip install gradio but I met another issue: Cache of C disk is not enough at this step: python gradio_app_sdxl_specific_id.py It would download about 40G models T T
> > 上述问题我问了AI，卸载再重装gradio就可以了，应该是版本问题。具体我忘了记下来版本号。。 先：pip uninstall gradio 然后: pip install gradio
> > 但是我遇到了另一个问题：执行python gradio_app_sdxl_specific_id.py 的时候，它要下载大概40G的模型。。。C盘不够用，该咋设置啊我草
> 
> 兄弟好样的 用你的办法解决了

你现在能跑了不，我卡在下模型哪儿了，是不是可以改cache默认下载路径啊，好头大 T T

**Comment by whmc76** [comment]
我跟你说 跑起来了 但是4090会显存不够用



---Original---
From: ***@***.***&gt;
Date: Sun, May 5, 2024 22:52 PM
To: ***@***.***&gt;;
Cc: "Cyber Dick ***@***.******@***.***&gt;;
Subject: Re: [HVision-NKU/StoryDiffusion] python.\gradio_app_sdxl_specific_id.py ERROR (Issue #21)




    
兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda
 python gradio_app_sdxl_specific_id.py Traceback (most recent call last): File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in import gradio as gr File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio__init__.py", line 3, in import gradio.simple_templates File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates__init_.py", line 1, in from .simpledropdown import SimpleDropdown File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates\simpledropdown.py", line 6, in from gradio.components.base import FormComponent File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components__init__.py", line 40, in from gradio.components.multimodal_textbox import MultimodalTextbox File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in class MultimodalTextbox(FormComponent): File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in new create_or_modify_pyi(component_class, name, events) File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi source_code = source_file.read_text() File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence
  
this issue is solved by AI: pip uninstall gradio then: pip install gradio but I met another issue: Cache of C disk is not enough at this step: python gradio_app_sdxl_specific_id.py It would download about 40G models T T
 上述问题我问了AI，卸载再重装gradio就可以了，应该是版本问题。具体我忘了记下来版本号。。 先：pip uninstall gradio 然后: pip install gradio
 但是我遇到了另一个问题：执行python gradio_app_sdxl_specific_id.py 的时候，它要下载大概40G的模型。。。C盘不够用，该咋设置啊我草
  
兄弟好样的 用你的办法解决了
  
你现在能跑了不，我卡在下模型哪儿了，是不是可以改cache默认下载路径啊，好头大 T T

**Comment by tiwentichat** [comment]
> 我跟你说 跑起来了 但是4090会显存不够用
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, May 5, 2024 22:52 PM To: ***@***.***&gt;; Cc: "Cyber Dick ***@***.******@***.***&gt;; Subject: Re: [HVision-NKU/StoryDiffusion] python.\gradio_app_sdxl_specific_id.py ERROR (Issue #21) 兄弟，这个问题解决了吗，我也卡在这儿了。。不过最后的报错是gbk codec， 我是win系统+miniconda python gradio_app_sdxl_specific_id.py Traceback (most recent call last): File "G:\0000000storydiffusion\gradio_app_sdxl_specific_id.py", line 2, in import gradio as gr File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio__init__.py", line 3, in import gradio.simple_templates File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates__init_.py", line 1, in from .simpledropdown import SimpleDropdown File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio_simple_templates\simpledropdown.py", line 6, in from gradio.components.base import FormComponent File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components__init__.py", line 40, in from gradio.components.multimodal_textbox import MultimodalTextbox File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in class MultimodalTextbox(FormComponent): File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 198, in new create_or_modify_pyi(component_class, name, events) File "G:\00miniconda\install\envs\storydiffusion\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi source_code = source_file.read_text() File "G:\00miniconda\install\envs\storydiffusion\lib\pathlib.py", line 1135, in read_text return f.read() UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence this issue is solved by AI: pip uninstall gradio then: pip install gradio but I met another issue: Cache of C disk is not enough at this step: python gradio_app_sdxl_specific_id.py It would download about 40G models T T 上述问题我问了AI，卸载再重装gradio就可以了，应该是版本问题。具体我忘了记下来版本号。。 先：pip uninstall gradio 然后: pip install gradio 但是我遇到了另一个问题：执行python gradio_app_sdxl_specific_id.py 的时候，它要下载大概40G的模型。。。C盘不够用，该咋设置啊我草 兄弟好样的 用你的办法解决了 你现在能跑了不，我卡在下模型哪儿了，是不是可以改cache默认下载路径啊，好头大 T T — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我草，哭死 T T

**Comment by Z-YuPeng** [comment]
@whmc76 现在更新code了，4090 是可以跑的，请查看首页readme.
