### ISSUE TITLE
Does not support multiple trigger words in a single prompt.

### ISSUE THREAD

**Issue by sp1cae** [HVision-NKU/StoryDiffusion#35]
ValueError: PhotoMaker currently does not support multiple trigger words in a single prompt.                            
Trigger word: img, Prompt: anime artwork illustrating  The car on the road, near the forest . created by japanese anime studio. highly emotional. best quality, high resolution.

**Comment by yratof** [comment]
Duplicate issue: https://github.com/HVision-NKU/StoryDiffusion/issues/27

**Comment by Z-YuPeng** [comment]
I have support nc in ref image mode now! Please git pull the lastest code.

This is an example.
![image - 2024-05-08T033055 535](https://github.com/HVision-NKU/StoryDiffusion/assets/49511209/e1dc58b4-13e9-49e7-ad00-dbb4b67c8a1b)

**Comment by Z-YuPeng** [comment]
I am closing this issue because it is a duplicate. If it did not solve your problem, feel free to reopen it.
