### ISSUE TITLE
SG161222--RealVisXL_V4.0项目的vae中缺少diffusion_pytorch_model.bin文件该如何解决

### ISSUE THREAD

**Issue by kangxi1818** [HVision-NKU/StoryDiffusion#38]
报错如下
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/117744200/414b37b0-4e13-4c94-9783-404f98c8e3f7)
但是该项目中本来就没有diffusion_pytorch_model.bin文件
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/117744200/cd93b046-3e14-458b-a517-8e2dc46c0292)

**Comment by Z-YuPeng** [comment]
HI, thanks for you feedback, whether you use the latest code and run
python gradio_app_sdxl_specific_id_low_vram.py   ?

**Comment by TonySCruze** [comment]
try adding use_safetensors=True to your pipeline
StableDiffusionXLPipeline.from_pretrained(sd_model_path, variant="fp16", torch_dtype=torch.float16, use_safetensors=True)

**Comment by xiehust** [comment]
@TonySCruze You are right~ Fixed it
