### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [HVision-NKU/StoryDiffusion#4]
Hi,
Thank you so much for releasing StoryDiffision! The results are incredible!
I wanted to run this locally and was wondering what the license to use this was. Might it be possible to add an open source license?
Thank you!

**Comment by Z-YuPeng** [comment]
Hi,Thanks for your attention. the license is Apache License 2.0. We will add
To Repo.

**Comment by fakerybakery** [comment]
Thank you! Excited for the video model release!
