### ISSUE TITLE
can this work on Mac M3 ? how much ram required for that ? 

### ISSUE THREAD

**Issue by scottonly2** [HVision-NKU/StoryDiffusion#42]

**Comment by Z-YuPeng** [comment]
@kellyzxiaowei  Could you make a pull request about it? Very thankful for your efforts.

**Comment by scottonly2** [comment]
How much RAM required to use the mps version ? will 16G enough , and is it possible to adjust with some settings

**Comment by scottonly2** [comment]
Hi kelly, can you check the error I report when run with mps ,  I tried with 16G RAM M3, with PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.5
