### ISSUE TITLE
在SD中找不到story diffusion

### ISSUE THREAD

**Issue by yuanjiajun999** [HVision-NKU/StoryDiffusion#43]
我已经通过网址下载tory diffusion了，并且在C:\stable-diffusion-webui\extensions\StoryDiffusion也安装了他，可是在webui界面却不显示找不到他是什么原因？

![Uploading 4931d7680a97f9f33df9f9043c1a8ad.png…]()

**Comment by longzy1** [comment]
这个压根就不是SD的插件- -

**Comment by Z-YuPeng** [comment]
@yuanjiajun999 我们计划开发webui,但是现在这个仓库不是webui插件，请参考readme 运行。
