### ISSUE TITLE
How much compute for training the motion predictor?

### ISSUE THREAD

**Issue by olliacc** [HVision-NKU/StoryDiffusion#6]

**Comment by zhoudaquan** [comment]
Hi, 

The motion predictor used 8 GPU cards for 3-4 days. In addition, we also train our self-owned motion module which uses 32 A100 GPU cards for one week. The motion predictor and the motion module is used together for the video result’s presented in the paper.

**Comment by zhoudaquan** [comment]
The main idea behind this way of video generation is to save the compute since image model is much more easier to train, compared to train a hyper-realistic video model directly.
