### ISSUE TITLE
Images Storage and empty Bubbles

### ISSUE THREAD

**Issue by mischaschaub** [HVision-NKU/StoryDiffusion#67]
I am doing long stories now with your great program. I would be helpful if I could have all images stored automatically in an output folder, ideally with their sequence number first, followed by their description. 

Super it would be as well if you could offer the option of having empty text bubbles, as they are filled with placeholder text and I have to erase and replace them with meaningful text.

**Comment by Z-YuPeng** [comment]
I am currently making significant changes to the code to support new features, such as saving and loading IDs, multiple characters, and more. I will add this functionality to the new version.

**Comment by mischaschaub** [comment]
May the force be with you!

**Comment by freya9933** [comment]
@mischaschaub @Z-YuPeng I'm also interested in long stories generation, may I ask how many frames can stroydiffusion generate at most?
