### ISSUE TITLE
About some details of paper

### ISSUE THREAD

**Issue by YahooKID** [HVision-NKU/StoryDiffusion#70]
Thanks for open source such a great model, here is a little my own problem about some details of paper,

1. About the training stage of transition video generation model, did you freeze the Motion Modeling Module which is from AnimateDiff, or SFT this module as well as training Semantic Space Motion Predictor(Transformer Block Part)?
2. About Training dataset Webvid-10M, as my known, almost all of video data in this dataset have the similar watermarks with the similar position, with my limited knowledge, these watermarks with similar features will influence the capability of model. If you take any preprocess could you share it with me?

Cheers

**Comment by brentjohnston** [comment]
Crickets for some reason, I'd like to know also.

**Comment by YahooKID** [comment]
> > Thanks for open source such a great model, here is a little my own problem about some details of paper,
> > 
> > 1. About the training stage of transition video generation model, did you freeze the Motion Modeling Module which is from AnimateDiff, or SFT this module as well as training Semantic Space Motion Predictor(Transformer Block Part)?
> > 2. About Training dataset Webvid-10M, as my known, almost all of video data in this dataset have the similar watermarks with the similar position, with my limited knowledge, these watermarks with similar features will influence the capability of model. If you take any preprocess could you share it with me?
> > 
> > Cheers
> 
> Hi,
> 
> Thank you for your interest in the work. 1. we train the motion predictor together with the motion module taken from AnimateDiff. Both modules are trainable. 2. Please refer to this repo for the watermark removal on WebVid dataset: https://github.com/RoundofThree/python-scripts/blob/1f9455ce9f5832883e1002e73934afa4099a097e/watermark_removal/watermark_remover.py#L188
> 
> Regards, Zhou Daquan

thanks.

**Comment by armored-guitar** [comment]
@zhoudaquan

**Comment by Z-YuPeng** [comment]
We encode a single image as N token vectors to represent different semantic information. Then we perform prediction. Thus, each intermediate frame corresponds to N tokens in the semantic space.
