### ISSUE TITLE
Many runs with different seeds

### ISSUE THREAD

**Issue by mischaschaub** [HVision-NKU/StoryDiffusion#78]
Would be great to be able to order a number of runs of each picture definition with different random seeds. I am doing movies with your great tool and this sure would be helpful!

**Comment by Z-YuPeng** [comment]
Do you usually work with ComfyUI? We are developing a ComfyUI version and plan to add such features. Of course, we can also try to add them to the Gradio version. I am currently making significant changes to the code to support some new features: for example, saving and loading of IDs, multiple characters, and so on.

**Comment by mischaschaub** [comment]
Oh this is such great news! Would be so much better with comfyUI, at least for me. Any order of magnitude about ETA would be helpful.
