### ISSUE TITLE
这是什么意思？ Number of id images in total images

### ISSUE THREAD

**Issue by aadian** [HVision-NKU/StoryDiffusion#80]
这个参数是什么意思？ Number of id images in total images

**Comment by lvalics** [comment]
The number of images is where it looks for the character inside the prompt. Normally, in the new version where we can name the character by name, I think this parameter is obsolete and will probably be removed.

**Comment by aadian** [comment]
> The number of images is where it looks for the character inside the prompt. Normally, in the new version where we can name the character by name, I think this parameter is obsolete and will probably be removed.

Understood. Thanks.
