### ISSUE TITLE
请问新更新的内容，支持多人，可以分别描绘不同人的单独动作么？还有提示词中是否支持对景别和人物角度的控制？

### ISSUE THREAD

**Issue by huanxve** [HVision-NKU/StoryDiffusion#86]
请问新更新的内容，支持多人，可以分别描绘不同人的单独动作么？还有提示词中是否支持对景别和人物角度的控制？

**Comment by Z-YuPeng** [comment]
理论上可以描绘，但是由于storydiffusion 基于 SDXL 能力, 太复杂的句子模型可能理解不了，你好可能会基于image composite 支持这些功能

**Comment by yishuaidu** [comment]
你好 如果是dit结构呢？
