### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

### ISSUE THREAD

**Issue by mikeyimer** [HVision-NKU/StoryDiffusion#9]
it seems unicode decoding error.
![story1](https://github.com/HVision-NKU/StoryDiffusion/assets/137673481/f8bc971b-279b-4911-bc43-b762b73b049c)
![story2](https://github.com/HVision-NKU/StoryDiffusion/assets/137673481/975bb3d6-d555-4b96-8320-c1f82f525ace)

**Comment by Z-YuPeng** [comment]
This might be an issue about gradio.
Maybe you can follow this: https://blog.csdn.net/weixin_44505135/article/details/136975419

**Comment by mikeyimer** [comment]
> This might be an issue about gradio. Maybe you can follow this: https://blog.csdn.net/weixin_44505135/article/details/136975419

Thank you,this link solved my problem.
