### ISSUE TITLE
gradio_app_sdxl_specific_id.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sugary199** [HVision-NKU/StoryDiffusion#94]
Hi,I was trying to use it but the entry file not found?

# python gradio_app_sdxl_specific_id.py
python: can't open file '/ML-A100/team/mm/shuyu/workspace/projects/StoryDiffusion/gradio_app_sdxl_specific_id.py': [Errno 2] No such file or directory

**Comment by Z-YuPeng** [comment]
python gradio_app_sdxl_specific_id_low_vram.py
